--drop all
DROP TABLE ACCOUNT_TX;
DROP TABLE MEMBER;
DROP TABLE EX_RATE;
DROP TABLE CURRENCY;

DROP SEQUENCE CURRENCY_ID_SEQ;
DROP SEQUENCE EX_RATE_ID_SEQ;
DROP SEQUENCE MEMBER_ID_SEQ;
DROP SEQUENCE ACCOUNT_ID_SEQ;

DROP TRIGGER CURRENCY_ID_TRG;
DROP TRIGGER EX_RATE_ID_TRG;
DROP TRIGGER MEMBER_ID_TRG;
DROP TRIGGER ACCOUNT_ID_TRG;


--create tables
CREATE TABLE CURRENCY(
    CURRENCY_ID         NUMBER(15)          PRIMARY KEY,
    CURRENCY_CREATION_DATE          DATE            DEFAULT SYSDATE         NOT NULL,
    CURRENCY_NAME           VARCHAR(20)         NOT NULL,
        CONSTRAINT          CURRENCY_NAME_UNI           UNIQUE(CURRENCY_NAME),
    CURRENCY_DESCRIPTION            VARCHAR(50)         NOT NULL);
    
    CREATE SEQUENCE CURRENCY_ID_SEQ;
    
    CREATE TRIGGER CURRENCY_ID_TRG
        BEFORE INSERT OR UPDATE OR DELETE ON CURRENCY
        FOR EACH ROW
        BEGIN
            SELECT CURRENCY_ID_SEQ.NEXTVAL
            INTO :NEW.CURRENCY_ID
            FROM DUAL;
        END;
        /
        
CREATE TABLE EX_RATE(
    EX_RATE_ID          NUMBER(15)          PRIMARY KEY,
    EX_RATE_DATE            DATE            DEFAULT SYSDATE         NOT NULL,
    EX_RATE         NUMBER(5,2)         DEFAULT 0.00            NOT NULL,
    CURRENCY_ID_BASE            NUMBER(15)         NOT NULL,
        CONSTRAINT CURRENCY_ID_BASE_EX_FK           FOREIGN KEY(CURRENCY_ID_BASE) REFERENCES CURRENCY(CURRENCY_ID),
    CURRENCY_ID         NUMBER(15)          NOT NULL,
        CONSTRAINT CURRENCY_ID_EX_FK           FOREIGN KEY(CURRENCY_ID) REFERENCES CURRENCY(CURRENCY_ID),
        CONSTRAINT DATE_BASE_RATE_UNI       UNIQUE(EX_RATE_DATE,CURRENCY_ID_BASE,CURRENCY_ID));        
    
    CREATE SEQUENCE EX_RATE_ID_SEQ;
    
    CREATE TRIGGER EX_RATE_ID_TRG
        BEFORE INSERT OR UPDATE OR DELETE ON EX_RATE
        FOR EACH ROW
        BEGIN
            SELECT EX_RATE_ID_SEQ.NEXTVAL
            INTO :NEW.CURRENCY_ID
            FROM DUAL;
        END;
         /
    
CREATE TABLE MEMBER(
    MEMBER_ID           NUMBER(15)          PRIMARY KEY,
    MEMBER_SUBSCRIBE_DATE           DATE            DEFAULT SYSDATE             NOT NULL,
    MEMBER_NAME         VARCHAR(20)         NOT NULL,
        CONSTRAINT MEMBER_NAME_UNI          UNIQUE(MEMBER_NAME));
    
    CREATE SEQUENCE MEMBER_ID_SEQ;
    
    CREATE TRIGGER MEMBER_ID_TRIG
        BEFORE INSERT OR UPDATE OR DELETE ON MEMBER
        FOR EACH ROW
        BEGIN 
            SELECT MEMBER_ID_SEQ.NEXTVAL
            INTO :NEW.MEMBER_ID
            FROM DUAL;
        END;
        /    
    
CREATE TABLE ACCOUNT_TX(
    ACCOUNT_TX_ID           NUMBER(15)          PRIMARY KEY,
    ACCOUNT_TX_DATE         DATE            DEFAULT SYSDATE         NOT NULL,
    ACCOUNT_TX_QUANTITY         NUMBER(10,2)          DEFAULT 0.00          NOT NULL,
    CURRENCY_ID         NUMBER(15),         
        CONSTRAINT CURRENCY_ID_ACCOUNT_FK           FOREIGN KEY(CURRENCY_ID) REFERENCES CURRENCY,
    MEMBER_ID           NUMBER(15),
        CONSTRAINT MEMBER_ID_ACCOUNT_FK         FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER);

    CREATE SEQUENCE ACCOUNT_ID_SEQ;
    
    CREATE TRIGGER ACCOUNT_ID_TRG
        BEFORE INSERT OR UPDATE OR DELETE ON ACCOUNT_TX
        FOR EACH ROW
        BEGIN
            SELECT ACCOUNT_ID_SEQ.NEXTVAL
            INTO :NEW.ACCOUNT_TX_ID
            FROM DUAL;
        END;
        /
       
 
        
        
    
